spring:
  application:
    name: openai
  ai:
    chat:
      memory:
        repository:
          jdbc:
            schema: classpath:schema/schema-h2db.sql
            initialize-schema: always
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        initialize-schema: true
        collection-name: ai-vectorstore
    openai:
      api-key: ${OPENAI_API_KEY}
  datasource:
    url: jdbc:h2:file:C:\\Users\\golla\\chatmemory;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: venky
    password: 12345
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  docker:
    compose:
      stop:
        command: down

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
server:
  port: 8090

audit:
  token-usage:
    enabled: true